//AUTOGENERATED FILE FROM png2asset
// Conversion args: \AstronautUp.png -sw 16 -sh 16 -keep_palette_order

#ifndef METASPRITE_AstronautUp_H
#define METASPRITE_AstronautUp_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define AstronautUp_TILE_ORIGIN 0
#define AstronautUp_TILE_W 8
#define AstronautUp_TILE_H 16
#define AstronautUp_WIDTH 16
#define AstronautUp_HEIGHT 16
#define AstronautUp_TILE_COUNT 8
#define AstronautUp_PALETTE_COUNT 1
#define AstronautUp_COLORS_PER_PALETTE 4
#define AstronautUp_TOTAL_COLORS 4
#define AstronautUp_PIVOT_X 8
#define AstronautUp_PIVOT_Y 8
#define AstronautUp_PIVOT_W 16
#define AstronautUp_PIVOT_H 16
extern const metasprite_t* const AstronautUp_metasprites[2];

BANKREF_EXTERN(AstronautUp)

extern const palette_color_t AstronautUp_palettes[4];
extern const uint8_t AstronautUp_tiles[128];

#endif
