//AUTOGENERATED FILE FROM png2asset
// Conversion args: \AstronautDown.png -sw 16 -sh 16 -keep_palette_order

#ifndef METASPRITE_AstronautDown_H
#define METASPRITE_AstronautDown_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define AstronautDown_TILE_ORIGIN 0
#define AstronautDown_TILE_W 8
#define AstronautDown_TILE_H 16
#define AstronautDown_WIDTH 16
#define AstronautDown_HEIGHT 16
#define AstronautDown_TILE_COUNT 8
#define AstronautDown_PALETTE_COUNT 1
#define AstronautDown_COLORS_PER_PALETTE 4
#define AstronautDown_TOTAL_COLORS 4
#define AstronautDown_PIVOT_X 8
#define AstronautDown_PIVOT_Y 8
#define AstronautDown_PIVOT_W 16
#define AstronautDown_PIVOT_H 16
extern const metasprite_t* const AstronautDown_metasprites[2];

BANKREF_EXTERN(AstronautDown)

extern const palette_color_t AstronautDown_palettes[4];
extern const uint8_t AstronautDown_tiles[128];

#endif
