//AUTOGENERATED FILE FROM png2asset
// Conversion args: AstronautRight.png -sw 16 -sh 16 -keep_palette_order

#ifndef METASPRITE_AstronautRight_H
#define METASPRITE_AstronautRight_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define AstronautRight_TILE_ORIGIN 0
#define AstronautRight_TILE_W 8
#define AstronautRight_TILE_H 16
#define AstronautRight_WIDTH 16
#define AstronautRight_HEIGHT 16
#define AstronautRight_TILE_COUNT 12
#define AstronautRight_PALETTE_COUNT 1
#define AstronautRight_COLORS_PER_PALETTE 4
#define AstronautRight_TOTAL_COLORS 4
#define AstronautRight_PIVOT_X 8
#define AstronautRight_PIVOT_Y 8
#define AstronautRight_PIVOT_W 16
#define AstronautRight_PIVOT_H 16
extern const metasprite_t* const AstronautRight_metasprites[3];

BANKREF_EXTERN(AstronautRight)

extern const palette_color_t AstronautRight_palettes[4];
extern const uint8_t AstronautRight_tiles[192];

#endif
