//AUTOGENERATED FILE FROM png2asset
// Conversion args: \Cat.png -sw 16 -sh 16 -keep_palette_order

#ifndef METASPRITE_Cat_H
#define METASPRITE_Cat_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define Cat_TILE_ORIGIN 0
#define Cat_TILE_W 8
#define Cat_TILE_H 16
#define Cat_WIDTH 16
#define Cat_HEIGHT 16
#define Cat_TILE_COUNT 24
#define Cat_PALETTE_COUNT 2
#define Cat_COLORS_PER_PALETTE 4
#define Cat_TOTAL_COLORS 8
#define Cat_PIVOT_X 8
#define Cat_PIVOT_Y 8
#define Cat_PIVOT_W 16
#define Cat_PIVOT_H 16
extern const metasprite_t* const Cat_metasprites[8];

BANKREF_EXTERN(Cat)

extern const palette_color_t Cat_palettes[8];
extern const uint8_t Cat_tiles[384];

#endif
