//AUTOGENERATED FILE FROM png2asset
// Conversion args: palettes.png -sw 16 -sh 16 -keep_palette_order

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

BANKREF(palettes)

const palette_color_t palettes_palettes[8] = {
	RGB8(  0, 57,115), RGB8(  0,  0,  0), RGB8( 16,173, 66), RGB8(255,189,140),
	RGB8(  0, 57,115), RGB8(  0,  0,  0), RGB8(255,189,140), RGB8( 25,132,255)
	};

const uint8_t palettes_tiles[32] = {
	0x55,0x33,0x48,0x34,0x4c,0x28,0xb1,0x25,0x29,0x00,0x8b,0xd9,0xa6,0x92,0x4f,0x24,
	0x54,0x40,0xe4,0x72,0x75,0x2c,0x9e,0xad,0xa9,0x32,0xb9,0xbc,0x53,0x01,0xec,0x88
	};

const metasprite_t palettes_metasprite0[] = {
	METASPR_ITEM(-8, -8, 0, S_PAL(0)),
	METASPR_TERM
};

const metasprite_t* const palettes_metasprites[1] = {
	palettes_metasprite0
};
