//AUTOGENERATED FILE FROM png2asset
// Conversion args: \palettes.png -sw 16 -sh 16 -keep_palette_order

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

BANKREF(palettes)

const palette_color_t palettes_palettes[8] = {
	RGB8(  0, 57,115), RGB8(  0,  0,  0), RGB8( 16,173, 66), RGB8(255,189,140),
	RGB8(  0, 57,115), RGB8(  0,  0,  0), RGB8(255,189,140), RGB8( 25,132,255)
	};

const uint8_t palettes_tiles[32] = {
	0x55,0x33,0x5c,0x38,0x4c,0x28,0x15,0x59,0x14,0x00,0xc5,0x6c,0xd3,0xc9,0x27,0x12,
	0xaa,0x20,0x72,0x39,0x75,0x2c,0x9e,0xad,0xa9,0x32,0x1d,0xc0,0x14,0x80,0xfb,0x62
	};

const metasprite_t palettes_metasprite0[] = {
	METASPR_ITEM(-8, -8, 0, S_PAL(0)),
	METASPR_TERM
};

const metasprite_t* const palettes_metasprites[1] = {
	palettes_metasprite0
};
